server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/auth-db?authSource=admin
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 5             # evalúa las últimas 5 llamadas
        failure-rate-threshold: 50         # si 50% fallan → abre el circuito
        wait-duration-in-open-state: 10s   # espera 10s antes de pasar a HALF-OPEN
        permitted-number-of-calls-in-half-open-state: 2

  timelimiter:
    instances:
      default:
        timeout-duration: 2s
kafka:
  topics:
    credit-card-check-request: credit-card-check-request
    credit-card-check-response: credit-card-check-response
    debt-check-request: debt-check-request  
    debt-check-response: debt-check-response
    transfer-request: transfer-request
    transfer-response: transfer-response
    debit-card-payment-request: debit-card-payment-request
    debit-card-payment-response: debit-card-payment-response
    yanki-link-debit-card-request: yanki-link-debit-card-request
    yanki-link-debit-card-response: yanki-link-debit-card-response
