server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - name: JwtAuthenticationFilter

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: JwtAuthenticationFilter

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/credits/**
          filters:
            - name: JwtAuthenticationFilter

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 5c37f932b2537f7bcaf700159774c748d7e1bcc372c35da906c9863116237f4a

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
